Feature/import proptypes properly
smaato/ui-framework pull request #335
Opened 2018-08-08 14:18 UTC by DarioG

2018-08-23 14:51 UTC, arijitdasgupta approved these changes
Looks Good! :rocket:

2018-08-24 12:52 UTC, alanbasse approved these changes
PR works with SDX so fine for me. 

Just one thing: We strive for alphabetic ordering within the imports as well, sorted by lib name like `'prop-types'` before `'react'`. It's not fully embraced yet anyway but in regards of uncle Bob...

2018-09-06 10:16 UTC, jenslonkowski commented on src/framework/appHeader/AppHeader.jsx
> +import PropTypes from 'prop-types';
You missed this one ;-)

2018-09-06 10:18 UTC, jenslonkowski commented on src/framework/chart/LineChart.jsx
>  import $ from 'jquery';
Maybe fix the order here as well ;-)

2018-09-06 10:53 UTC, jenslonkowski commented on src/framework/viewHeader/dateRange/DateRange.jsx
> +import { DateRange as ReactDateRange } from 'react-date-range';
Why did you move this line down?

2018-09-06 11:00 UTC, jenslonkowski commented on src/guide/components/sourceCodeViewer/SourceCodeViewer.jsx
>  import $ from 'jquery';
"jquery" needs to go below "highlight.js"

2018-09-06 11:00 UTC, jenslonkowski commented on src/guide/views/AppView.jsx
> +import $ from 'jquery';
"jquery" needs to go below "classnames"

2018-09-06 11:02 UTC, jenslonkowski requested changes
Just some minor order fixes required. Good job Dario!

2018-09-06 11:04 UTC, jenslonkowski commented on src/framework/base/dropdown/BaseDropdown.jsx
>  import $ from 'jquery';
"jquery" needs to go below "classnames"

2018-09-13 09:53 UTC, jenslonkowski commented on src/guide/components/sourceCodeViewer/SourceCodeViewer.jsx
> +import $ from 'jquery';
...hij... -> one more line down please ;-)

2018-09-13 10:09 UTC, jenslonkowski approved these changes
Great work!

2018-09-20 10:02 UTC, merged